spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
    open-in-view: false

jwt:
  secret:
    key: 7JWI64WV7ZWY7IS47JqU6rmA6r6466+47J6F64uI64uk7K2I6r647K2I6r647K2I6r647K2I6r64
  access:
    time: 1800000     # 30분
  refresh:
    time: 1209600000    # 14일

admin:
  secret:
    key: AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC